config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  root 'welcome#index'
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # has_many :posts, dependent: :destroy
  belongs_to :user
  validates :name, presence: true
  # mms: is all of this information required for every dog?
  # mms: is this Profile for an organization or a dog?  I expected an organization too have a profile.  Each Organization would have many adoptees (puppies).
  validates :age, presence: true
  validates :breed, presence: true
  validates :gender, presence: true
  validates :city, presence: true
  validates :state, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def sort
    session[:sort_by] = params[:sort_by]
    redirect_to profiles_path
  end

  def index
    @profiles = current_user.profiles
    # @user = User.find(session[:user]["id"])
    # @profiles = User.find(session[:user]["id"]).profiles
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.profiles.create!(profile_params)
    # @profile = Profile.create!(profile_params)
    # @user = current_user
    # @profile = current_user.profiles.create!(profile_params)
    # @user.profiles.create(user: current_user)
    # if @profile.save
      # flash[:notice] = "#{@profile.name} was successfully created."
      @profiles = current_user.profiles
      # redirect_to @profiles
      render :show
    # else
      # render :new
    # end
  end


  def show
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      flash[:notice] = "#{@profile.name} was successfully updated."
      redirect_to @profile
    else
      render :edit
    end
  end


  def destroy

  end

  private
  def profile_params
    params.require(:profile).permit(:name, :gender, :breed, :city, :state, :age, :pro_pic, :description)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@profile.errors.count, "error") %> prohibited
        this profile from being saved:
      </h2>
      <ul>
        <% @profile.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel panel-default">
    <div class="panel-heading">

    </div>
    <div class="panel-body">
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :gender %>
          <%= f.select :gender, [["Male", "Male"], ["Female", "Female"]], autocomplete: "off", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :breed %>
          <%= f.text_field :breed, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :city %>
          <%= f.text_field :city, autofocus: true, class: "form-control" %>
        </div>

        <div class="form-group">
           <%= select_tag 'State', options_for_select(us_states),:name=>"profile[state]",:id=>"state" %>
        </div>
        <div class="form-group">
          <%= f.label :age %>
          <%= f.text_field :age, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%=f.label :profile_Picture %>
          <%= f.text_field :pro_pic, class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.label :description %>
           <%= f.text_area :description, class: "form-control" %>
         </div>
        <%= f.submit %>
<%end%>

app/views/profiles/edit.html.erb
<h1>Edit Profile</h1>

<!-- refer to profiles/_form.html.erb -->
<%= render 'form' %>

<!-- Delete profile -->
<%= link_to 'Delete!', profile_path(@profile), method: :delete, class: 'delete' %>

app/views/profiles/index.html.erb
<h1>My Profiles</h1>


<div class='container'>
      <div class='row'>
    <% @profiles.each do |profile| %>

        <div class="col-md-3">
          <div class='caption'>
            <h2><%= profile.name %></h2>
          <div class='thumbnail'>
            <img><%= image_tag profile.pro_pic %></img>
          </div>

          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>
<!-- refer to profiles/_form.html.erb -->
<%= render 'form' %>

app/views/profiles/show.html.erb
<h1><%= @profile.name%></h1>
<div class:'location'>
  <p>City: <%= @profile.city %></p>
  <p>State: <%= @profile.state %></p>
</div>

<div class:'info'>
  <p>Breed: <%= @profile.breed %></p>
  <p>Age: <%= @profile.age %></p>
  <p>Gender: <%= @profile.gender %></p>
  <img><%= image_tag @profile.pro_pic %></img>
  <p>Description <%= @profile.description %>
</div>
<p>  <%= link_to 'User Profile', profiles_path %></p>