config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles
  root 'welcome#index'
  devise_for :users, controllers: { registrations: 'users/registrations', passwords: 'users/passwords' }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>AllAboutChew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- mms: indentation -->
  <div class="jumbotron">
  <div class="container">
    <h1> All About Chew </h1>

  </div>
</div>

  <div class='container'>
    <ul class="nav navbar-nav navbar-left">

      <% if current_user %>
        <!-- mms: recommend you move "home" link out of conditional.  It is alsways shown -->
        <li><%= link_to 'Home', root_path%></li>
        <li><%= link_to 'New Profile', new_profile_path %></li>
      <% else %>
        <li><%= link_to 'Home', root_path%></li>
        <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class='placeholder'><%= link_to 'Search', root_path %></li>
      <% if current_user %>
        <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Signup', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>

  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>